foreach(required UPT07_REFLECTION UPT07_DISASSEMBLY UPT07_STAMP)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "UPT-07 temporal ownership verification missing ${required}")
    endif()
endforeach()

file(READ "${UPT07_REFLECTION}" reflection)
file(READ "${UPT07_DISASSEMBLY}" disassembly)

foreach(binding RANGE 0 3)
    if(NOT reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
        message(FATAL_ERROR "UPT-07 ownership proof lacks set 0 binding ${binding}")
    endif()
endforeach()
string(REGEX MATCHALL "\"binding\"[ \t]*:" bindings "${reflection}")
list(LENGTH bindings binding_count)
if(NOT binding_count EQUAL 4)
    message(FATAL_ERROR "UPT-07 ownership proof must expose exactly four descriptor bindings")
endif()
string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*176" surface_strides "${reflection}")
list(LENGTH surface_strides surface_stride_count)
if(NOT surface_stride_count EQUAL 1)
    message(FATAL_ERROR "UPT-07 ownership proof must expose the shared 176-byte surface element type")
endif()
string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*64" reservoir_strides "${reflection}")
list(LENGTH reservoir_strides reservoir_stride_count)
if(NOT reservoir_stride_count EQUAL 2)
    message(FATAL_ERROR "UPT-07 ownership proof must expose 64-byte SRV and UAV reservoir element types")
endif()
if(NOT reflection MATCHES "\"workgroup_size\"[ \t\r\n]*:[ \t\r\n]*\[[ \t\r\n]*8[ \t]*,[ \t\r\n]*8")
    message(FATAL_ERROR "UPT-07 ownership proof workgroup is not 8x8")
endif()
if(disassembly MATCHES "OpTraceRayKHR|OpRayQuery|OpImageSample|OpImageFetch|OpTypeImage")
    message(FATAL_ERROR "UPT-07 ownership proof admitted forbidden ray or texture work")
endif()
if(disassembly MATCHES "OpCapability (Int16|Float16)" OR
   disassembly MATCHES "OpType(Int|Float) 16")
    message(FATAL_ERROR "UPT-07 ownership proof introduced uncontracted native 16-bit SPIR-V")
endif()

file(WRITE "${UPT07_STAMP}"
    "UPT-07 temporal ownership verified: current-only in-place output, separate history page, 2x176-byte surfaces, 2x64-byte reservoirs, exact projected pixel, 8x8, no rays/textures/native16\n")
