foreach(required UPT07_FULL_REFLECTION UPT07_FULL_DISASSEMBLY
        UPT07_COMPACT_REFLECTION UPT07_COMPACT_DISASSEMBLY UPT07_STAMP)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "UPT-07 direct temporal verification missing ${required}")
    endif()
endforeach()

file(READ "${UPT07_FULL_REFLECTION}" full_reflection)
file(READ "${UPT07_FULL_DISASSEMBLY}" full_disassembly)
file(READ "${UPT07_COMPACT_REFLECTION}" compact_reflection)
file(READ "${UPT07_COMPACT_DISASSEMBLY}" compact_disassembly)

foreach(kind full compact)
    foreach(binding RANGE 0 5)
        if(NOT ${kind}_reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
            message(FATAL_ERROR "UPT-07 ${kind} direct temporal lacks set 0 binding ${binding}")
        endif()
    endforeach()
    string(REGEX MATCHALL "\"binding\"[ \t]*:" bindings "${${kind}_reflection}")
    list(LENGTH bindings binding_count)
    if(NOT binding_count EQUAL 6)
        message(FATAL_ERROR "UPT-07 ${kind} direct temporal must expose exactly six descriptor bindings")
    endif()
    if(NOT ${kind}_reflection MATCHES "\"array_stride\"[ \t]*:[ \t]*176")
        message(FATAL_ERROR "UPT-07 ${kind} direct temporal lacks the canonical 176-byte surface type")
    endif()
    if(NOT ${kind}_reflection MATCHES "\"workgroup_size\"[ \t\r\n]*:[ \t\r\n]*\[[ \t\r\n]*8[ \t]*,[ \t\r\n]*8")
        message(FATAL_ERROR "UPT-07 ${kind} direct temporal workgroup is not 8x8")
    endif()
    if(NOT ${kind}_reflection MATCHES "\"name\"[ \t]*:[ \t]*\"maximumHistoryAge\",[ \t\r\n]*\"type\"[ \t]*:[ \t]*\"uint\",[ \t\r\n]*\"offset\"[ \t]*:[ \t]*44" OR
       NOT ${kind}_reflection MATCHES "\"name\"[ \t]*:[ \t]*\"previousCamera\",[ \t\r\n]*\"type\"[ \t]*:[ \t]*\"_[0-9]+\",[ \t\r\n]*\"offset\"[ \t]*:[ \t]*48")
        message(FATAL_ERROR "UPT-07 ${kind} direct temporal push constants are not the frozen 112-byte layout")
    endif()
    string(REGEX MATCHALL "OpRayQueryInitializeKHR" ray_queries "${${kind}_disassembly}")
    list(LENGTH ray_queries ray_query_count)
    if(NOT ray_query_count EQUAL 1 OR ${kind}_disassembly MATCHES "OpTraceRayKHR")
        message(FATAL_ERROR "UPT-07 ${kind} direct temporal must expose exactly one bounded RayQuery trace site")
    endif()
    if(${kind}_disassembly MATCHES "OpImageSample|OpImageFetch|OpTypeImage")
        message(FATAL_ERROR "UPT-07 ${kind} direct temporal admitted texture/image work")
    endif()
    if(${kind}_disassembly MATCHES "OpCapability (Int16|Float16)" OR
       ${kind}_disassembly MATCHES "OpType(Int|Float) 16")
        message(FATAL_ERROR "UPT-07 ${kind} direct temporal introduced native 16-bit SPIR-V")
    endif()
endforeach()

string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*64" full_64 "${full_reflection}")
list(LENGTH full_64 full_64_count)
if(NOT full_64_count EQUAL 2 OR NOT full_reflection MATCHES "\"array_stride\"[ \t]*:[ \t]*112")
    message(FATAL_ERROR "UPT-07 full direct temporal must expose two 64-byte pages and one 112-byte light stream")
endif()
string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*64" compact_64 "${compact_reflection}")
list(LENGTH compact_64 compact_64_count)
if(NOT compact_64_count EQUAL 3 OR compact_reflection MATCHES "\"array_stride\"[ \t]*:[ \t]*112")
    message(FATAL_ERROR "UPT-07 compact direct temporal must expose two pages plus one 64-byte light stream and no 112-byte light stream")
endif()

file(WRITE "${UPT07_STAMP}"
    "UPT-07 direct temporal verified: six bindings, canonical current/previous surfaces, two 64-byte pages, full/compact light variants, one bounded RayQuery trace site, no textures/native16\n")
