foreach(required
        UPT04_DIRECT_RQ_REFLECTION UPT04_DIRECT_RQ_DISASSEMBLY UPT04_DIRECT_RQ_SPV
        UPT04_DIRECT_RG_REFLECTION UPT04_DIRECT_RG_DISASSEMBLY UPT04_DIRECT_RG_SPV
        UPT04_INDIRECT_RQ_REFLECTION UPT04_INDIRECT_RQ_DISASSEMBLY UPT04_INDIRECT_RQ_SPV
        UPT04_INDIRECT_RG_REFLECTION UPT04_INDIRECT_RG_DISASSEMBLY UPT04_INDIRECT_RG_SPV
        UPT04_UNIFIED_RQ_SPV UPT04_UNIFIED_RG_SPV UPT04_STAMP)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "UPT-04 static-specialization verification missing ${required}")
    endif()
endforeach()

foreach(kind DIRECT_RQ DIRECT_RG INDIRECT_RQ INDIRECT_RG)
    file(READ "${UPT04_${kind}_REFLECTION}" reflection)
    file(READ "${UPT04_${kind}_DISASSEMBLY}" disassembly)
    if(kind MATCHES "^DIRECT_")
        # Direct-only still needs the material table, sampler, and bindless
        # textures for exact emissive-triangle endpoint replay.  Removing them
        # silently collapses textured emitters to their constant material tint:
        # the primary surface glows, but the light proposal cannot cast that
        # texture's radiance into the scene.
        set(required_bindings 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 25 26 28 29)
        set(forbidden_bindings 22 27)
        set(expected_descriptor_count 27)
        set(expected_112_count 3)
        set(expected_64_count 2)
    else()
        set(required_bindings 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22)
        set(forbidden_bindings)
        set(expected_descriptor_count 24)
        set(expected_112_count 3)
        set(expected_64_count 1)
    endif()
    foreach(binding IN LISTS required_bindings)
        if(NOT reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
            message(FATAL_ERROR "UPT-04 ${kind} reflection lacks set 0 binding ${binding}")
        endif()
    endforeach()
    foreach(binding IN LISTS forbidden_bindings)
        if(reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}([, \t\r\n}]|$)")
            message(FATAL_ERROR "UPT-04 ${kind} unexpectedly retains set 0 binding ${binding}")
        endif()
    endforeach()
    if(NOT reflection MATCHES "\"set\"[ \t]*:[ \t]*1,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*0")
        message(FATAL_ERROR "UPT-04 ${kind} reflection lacks shared set 1 texture binding")
    endif()
    string(REGEX MATCHALL "\"binding\"[ \t]*:" descriptor_bindings "${reflection}")
    list(LENGTH descriptor_bindings descriptor_count)
    if(NOT descriptor_count EQUAL expected_descriptor_count)
        message(FATAL_ERROR "UPT-04 ${kind} exposes ${descriptor_count} descriptors; expected ${expected_descriptor_count}")
    endif()
    foreach(stride 4 36 64 80 112 144 176)
        string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*${stride}" stride_matches "${reflection}")
        list(LENGTH stride_matches stride_count)
        if(stride EQUAL 112)
            set(expected_count ${expected_112_count})
        elseif(stride EQUAL 64)
            set(expected_count ${expected_64_count})
        elseif(stride EQUAL 144)
            set(expected_count 2)
        else()
            set(expected_count 1)
        endif()
        if(NOT stride_count EQUAL expected_count)
            message(FATAL_ERROR
                "UPT-04 ${kind} has ${stride_count} declarations at stride ${stride}; expected ${expected_count}")
        endif()
    endforeach()
    string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*16" stride_16_matches "${reflection}")
    list(LENGTH stride_16_matches stride_16_count)
    if(kind MATCHES "^DIRECT_")
        if(NOT stride_16_count EQUAL 1)
            message(FATAL_ERROR "UPT-04 ${kind} must expose one emissive-distribution stride")
        endif()
    elseif(NOT stride_16_count EQUAL 1)
        message(FATAL_ERROR "UPT-04 ${kind} must expose one emissive lookup stride")
    endif()
    if(NOT reflection MATCHES "\"name\"[ \t]*:[ \t]*\"emissiveDistributionCountAndValid\",[ \t\r\n]*\"type\"[ \t]*:[ \t]*\"uint\",[ \t\r\n]*\"offset\"[ \t]*:[ \t]*188")
        message(FATAL_ERROR "UPT-04 ${kind} push constants are not 192 bytes")
    endif()
    if(kind MATCHES "_RQ$")
        if(NOT reflection MATCHES "\"workgroup_size\"[ \t\r\n]*:[ \t\r\n]*\\[[ \t\r\n]*8[ \t]*,[ \t\r\n]*8")
            message(FATAL_ERROR "UPT-04 ${kind} workgroup is not 8x8")
        endif()
    elseif(NOT disassembly MATCHES "OpEntryPoint RayGenerationKHR")
        message(FATAL_ERROR "UPT-04 ${kind} is not a Vulkan ray-generation stage")
    endif()
endforeach()

file(READ "${UPT04_DIRECT_RQ_DISASSEMBLY}" direct_rq_disassembly)
file(READ "${UPT04_DIRECT_RG_DISASSEMBLY}" direct_rg_disassembly)
file(READ "${UPT04_INDIRECT_RQ_DISASSEMBLY}" indirect_rq_disassembly)
file(READ "${UPT04_INDIRECT_RG_DISASSEMBLY}" indirect_rg_disassembly)
string(REGEX MATCHALL "OpRayQueryInitializeKHR" direct_rq_traces "${direct_rq_disassembly}")
string(REGEX MATCHALL "OpTraceRayKHR" direct_rg_traces "${direct_rg_disassembly}")
string(REGEX MATCHALL "OpRayQueryInitializeKHR" indirect_rq_traces "${indirect_rq_disassembly}")
string(REGEX MATCHALL "OpTraceRayKHR" indirect_rg_traces "${indirect_rg_disassembly}")
list(LENGTH direct_rq_traces direct_rq_count)
list(LENGTH direct_rg_traces direct_rg_count)
list(LENGTH indirect_rq_traces indirect_rq_count)
list(LENGTH indirect_rg_traces indirect_rg_count)
if(NOT direct_rq_count EQUAL 1 OR direct_rq_disassembly MATCHES "OpTraceRayKHR")
    message(FATAL_ERROR "UPT-04 direct-only RayQuery must have one RayQuery trace site")
endif()
if(NOT direct_rg_count EQUAL 1 OR direct_rg_disassembly MATCHES "OpRayQueryInitializeKHR")
    message(FATAL_ERROR "UPT-04 direct-only raygen must have one TraceRay site")
endif()
if(NOT indirect_rq_count EQUAL 2 OR indirect_rq_disassembly MATCHES "OpTraceRayKHR")
    message(FATAL_ERROR "UPT-04 indirect-only RayQuery must have two RayQuery trace sites")
endif()
if(NOT indirect_rg_count EQUAL 2 OR indirect_rg_disassembly MATCHES "OpRayQueryInitializeKHR")
    message(FATAL_ERROR "UPT-04 indirect-only raygen must have two TraceRay sites")
endif()

file(SIZE "${UPT04_DIRECT_RQ_SPV}" direct_rq_bytes)
file(SIZE "${UPT04_DIRECT_RG_SPV}" direct_rg_bytes)
file(SIZE "${UPT04_INDIRECT_RQ_SPV}" indirect_rq_bytes)
file(SIZE "${UPT04_INDIRECT_RG_SPV}" indirect_rg_bytes)
file(SIZE "${UPT04_UNIFIED_RQ_SPV}" unified_rq_bytes)
file(SIZE "${UPT04_UNIFIED_RG_SPV}" unified_rg_bytes)
if(NOT direct_rq_bytes LESS unified_rq_bytes
        OR NOT indirect_rq_bytes LESS unified_rq_bytes
        OR NOT direct_rg_bytes LESS unified_rg_bytes
        OR NOT indirect_rg_bytes LESS unified_rg_bytes)
    message(FATAL_ERROR "UPT-04 static family closure did not remove unified-family code")
endif()

file(WRITE "${UPT04_STAMP}"
    "UPT-04 static specializations verified: direct rq/rg=${direct_rq_bytes}/${direct_rg_bytes}, indirect rq/rg=${indirect_rq_bytes}/${indirect_rg_bytes}, unified rq/rg=${unified_rq_bytes}/${unified_rg_bytes}\n")
