foreach(required UPT04_GEOMETRY_REFLECTION UPT04_GEOMETRY_DISASSEMBLY UPT04_STAMP)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "UPT-04 geometry verification missing ${required}")
    endif()
endforeach()

file(READ "${UPT04_GEOMETRY_REFLECTION}" reflection)
file(READ "${UPT04_GEOMETRY_DISASSEMBLY}" disassembly)

if(NOT reflection MATCHES "\"workgroup_size\"[ \t\r\n]*:[ \t\r\n]*\\[[ \t\r\n]*8[ \t]*,[ \t\r\n]*8")
    message(FATAL_ERROR "UPT-04 geometry probe workgroup is not 8x8")
endif()
if(disassembly MATCHES "OpTraceRayKHR|OpRayQuery")
    message(FATAL_ERROR "UPT-04 geometry decoder probe must remain trace-free")
endif()

foreach(binding RANGE 1 21)
    if(NOT reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
        message(FATAL_ERROR "UPT-04 geometry reflection lacks set 0 binding ${binding}")
    endif()
endforeach()
if(reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*0")
    message(FATAL_ERROR "UPT-04 trace-free geometry probe unexpectedly retains the TLAS binding")
endif()
if(NOT reflection MATCHES "\"set\"[ \t]*:[ \t]*1,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*0")
    message(FATAL_ERROR "UPT-04 geometry reflection lacks shared set 1 texture binding")
endif()
string(REGEX MATCHALL "\"binding\"[ \t]*:" descriptor_bindings "${reflection}")
list(LENGTH descriptor_bindings descriptor_binding_count)
if(NOT descriptor_binding_count EQUAL 22)
    message(FATAL_ERROR "UPT-04 geometry probe must expose exactly 22 descriptor bindings")
endif()

foreach(stride 4 36 64 80 112 144 176)
    string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*${stride}" stride_matches "${reflection}")
    list(LENGTH stride_matches stride_count)
    if(stride EQUAL 112)
        set(expected_count 3)
    elseif(stride EQUAL 144)
        set(expected_count 2)
    else()
        set(expected_count 1)
    endif()
    if(NOT stride_count EQUAL expected_count)
        message(FATAL_ERROR
            "UPT-04 geometry reflection has ${stride_count} declarations at stride ${stride}; expected ${expected_count}")
    endif()
endforeach()
if(NOT reflection MATCHES "\"name\"[ \t]*:[ \t]*\"emissiveReplayCount\",[ \t\r\n]*\"type\"[ \t]*:[ \t]*\"uint\",[ \t\r\n]*\"offset\"[ \t]*:[ \t]*124")
    message(FATAL_ERROR "UPT-04 geometry push constants are not the frozen 128-byte layout")
endif()

file(WRITE "${UPT04_STAMP}"
    "UPT-04 geometry closure verified: trace-free, bindings=set0[1..21]+set1[0], strides=4/36/64/80/112/144x2/176, push=128\n")
