foreach(required UPT04_RAYQUERY_REFLECTION UPT04_RAYQUERY_DISASSEMBLY
        UPT04_RAYGEN_REFLECTION UPT04_RAYGEN_DISASSEMBLY
        UPT04_MISS_DISASSEMBLY UPT04_CLOSEST_HIT_DISASSEMBLY UPT04_STAMP)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "UPT-04 backend verification missing ${required}")
    endif()
endforeach()

file(READ "${UPT04_RAYQUERY_REFLECTION}" rayquery_reflection)
file(READ "${UPT04_RAYQUERY_DISASSEMBLY}" rayquery_disassembly)
file(READ "${UPT04_RAYGEN_REFLECTION}" raygen_reflection)
file(READ "${UPT04_RAYGEN_DISASSEMBLY}" raygen_disassembly)
file(READ "${UPT04_MISS_DISASSEMBLY}" miss_disassembly)
file(READ "${UPT04_CLOSEST_HIT_DISASSEMBLY}" closest_hit_disassembly)

foreach(kind rayquery raygen)
    foreach(stride 4 36 64 80 112 144 176)
        string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*${stride}" stride_matches "${${kind}_reflection}")
        list(LENGTH stride_matches stride_count)
        if(stride EQUAL 112)
            set(expected_count 3)
        elseif(stride EQUAL 144)
            set(expected_count 2)
        else()
            set(expected_count 1)
        endif()
        if(NOT stride_count EQUAL expected_count)
            message(FATAL_ERROR
                "UPT-04 ${kind} has ${stride_count} declarations at stride ${stride}; expected ${expected_count}")
        endif()
    endforeach()
    foreach(binding RANGE 0 21)
        if(NOT ${kind}_reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
            message(FATAL_ERROR "UPT-04 ${kind} reflection lacks set 0 binding ${binding}")
        endif()
    endforeach()
    if(NOT ${kind}_reflection MATCHES "\"set\"[ \t]*:[ \t]*1,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*0")
        message(FATAL_ERROR "UPT-04 ${kind} reflection lacks shared set 1 texture binding")
    endif()
    string(REGEX MATCHALL "\"binding\"[ \t]*:" descriptor_bindings "${${kind}_reflection}")
    list(LENGTH descriptor_bindings descriptor_binding_count)
    if(NOT descriptor_binding_count EQUAL 23)
        message(FATAL_ERROR "UPT-04 ${kind} must expose exactly 23 descriptor bindings")
    endif()
    if(NOT ${kind}_reflection MATCHES "\"name\"[ \t]*:[ \t]*\"emissiveReplayCount\",[ \t\r\n]*\"type\"[ \t]*:[ \t]*\"uint\",[ \t\r\n]*\"offset\"[ \t]*:[ \t]*124")
        message(FATAL_ERROR "UPT-04 ${kind} push constants are not the frozen 128-byte layout")
    endif()
endforeach()

if(NOT rayquery_reflection MATCHES "\"workgroup_size\"[ \t\r\n]*:[ \t\r\n]*\[[ \t\r\n]*8[ \t]*,[ \t\r\n]*8")
    message(FATAL_ERROR "UPT-04 RayQuery workgroup is not 8x8")
endif()
string(REGEX MATCHALL "OpRayQueryInitializeKHR" rayquery_instructions "${rayquery_disassembly}")
list(LENGTH rayquery_instructions rayquery_instruction_count)
if(NOT rayquery_instruction_count EQUAL 2 OR rayquery_disassembly MATCHES "OpTraceRayKHR")
    message(FATAL_ERROR "UPT-04 RayQuery closure must expose exactly two bounded trace sites")
endif()
string(REGEX MATCHALL "OpTraceRayKHR" traceray_instructions "${raygen_disassembly}")
list(LENGTH traceray_instructions traceray_instruction_count)
if(NOT traceray_instruction_count EQUAL 2 OR raygen_disassembly MATCHES "OpRayQueryInitializeKHR")
    message(FATAL_ERROR "UPT-04 raygen closure must expose exactly two bounded trace sites")
endif()
if(NOT miss_disassembly MATCHES "OpEntryPoint MissKHR")
    message(FATAL_ERROR "UPT-04 miss module is not a Vulkan miss stage")
endif()
if(NOT closest_hit_disassembly MATCHES "OpEntryPoint ClosestHitKHR")
    message(FATAL_ERROR "UPT-04 closest-hit module is not a Vulkan closest-hit stage")
endif()
if(NOT closest_hit_disassembly MATCHES "Upt04HitFacts = OpTypeStruct %uint %uint %uint %uint %v2float %float %uint")
    message(FATAL_ERROR "UPT-04 ray payload is not the frozen 32-byte compact hit-facts shape")
endif()

file(WRITE "${UPT04_STAMP}"
    "UPT-04 backend closure verified: unified set0[0..21]+set1[0], live strides=4/36/64/80/112x3/144x2/176, hit facts=32, bounded trace sites=2, RayQuery/raygen adapters isolated\n")
