foreach(required UPT04_RAYQUERY_REFLECTION UPT04_RAYQUERY_DISASSEMBLY
        UPT04_RAYGEN_REFLECTION UPT04_RAYGEN_DISASSEMBLY
        UPT04_MISS_DISASSEMBLY UPT04_CLOSEST_HIT_DISASSEMBLY UPT04_STAMP)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "UPT-04 backend verification missing ${required}")
    endif()
endforeach()

file(READ "${UPT04_RAYQUERY_REFLECTION}" rayquery_reflection)
file(READ "${UPT04_RAYQUERY_DISASSEMBLY}" rayquery_disassembly)
file(READ "${UPT04_RAYGEN_REFLECTION}" raygen_reflection)
file(READ "${UPT04_RAYGEN_DISASSEMBLY}" raygen_disassembly)
file(READ "${UPT04_MISS_DISASSEMBLY}" miss_disassembly)
file(READ "${UPT04_CLOSEST_HIT_DISASSEMBLY}" closest_hit_disassembly)

foreach(kind rayquery raygen)
    foreach(stride 176 64)
        if(NOT ${kind}_reflection MATCHES "\"array_stride\"[ \t]*:[ \t]*${stride}")
            message(FATAL_ERROR "UPT-04 ${kind} reflection lacks required ${stride}-byte live ABI")
        endif()
    endforeach()
    string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*112" stride_112_matches "${${kind}_reflection}")
    list(LENGTH stride_112_matches stride_112_count)
    if(NOT stride_112_count EQUAL 2)
        message(FATAL_ERROR "UPT-04 ${kind} must expose exactly two 112-byte light/material records")
    endif()
    foreach(binding 0 1 2 3 4 5)
        if(NOT ${kind}_reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
            message(FATAL_ERROR "UPT-04 ${kind} reflection lacks set 0 binding ${binding}")
        endif()
    endforeach()
    if(NOT ${kind}_reflection MATCHES "\"set\"[ \t]*:[ \t]*1,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*0")
        message(FATAL_ERROR "UPT-04 ${kind} reflection lacks shared set 1 texture binding")
    endif()
    string(REGEX MATCHALL "\"binding\"[ \t]*:" descriptor_bindings "${${kind}_reflection}")
    list(LENGTH descriptor_bindings descriptor_binding_count)
    if(NOT descriptor_binding_count EQUAL 7)
        message(FATAL_ERROR "UPT-04 ${kind} must expose exactly seven descriptor bindings")
    endif()
    if(NOT ${kind}_reflection MATCHES "\"name\"[ \t]*:[ \t]*\"currentLightCount\",[ \t\r\n]*\"type\"[ \t]*:[ \t]*\"uint\",[ \t\r\n]*\"offset\"[ \t]*:[ \t]*80")
        message(FATAL_ERROR "UPT-04 ${kind} push constants are not the frozen 84-byte layout")
    endif()
endforeach()

if(NOT rayquery_reflection MATCHES "\"workgroup_size\"[ \t\r\n]*:[ \t\r\n]*\[[ \t\r\n]*8[ \t]*,[ \t\r\n]*8")
    message(FATAL_ERROR "UPT-04 RayQuery workgroup is not 8x8")
endif()
if(NOT rayquery_disassembly MATCHES "OpRayQueryInitializeKHR" OR rayquery_disassembly MATCHES "OpTraceRayKHR")
    message(FATAL_ERROR "UPT-04 RayQuery adapter has the wrong ray instruction closure")
endif()
if(NOT raygen_disassembly MATCHES "OpTraceRayKHR" OR raygen_disassembly MATCHES "OpRayQueryInitializeKHR")
    message(FATAL_ERROR "UPT-04 raygen adapter has the wrong ray instruction closure")
endif()
if(NOT miss_disassembly MATCHES "OpEntryPoint MissKHR")
    message(FATAL_ERROR "UPT-04 miss module is not a Vulkan miss stage")
endif()
if(NOT closest_hit_disassembly MATCHES "OpEntryPoint ClosestHitKHR")
    message(FATAL_ERROR "UPT-04 closest-hit module is not a Vulkan closest-hit stage")
endif()
if(NOT closest_hit_disassembly MATCHES "Upt04HitFacts = OpTypeStruct %uint %uint %uint %uint %v2float %float %uint")
    message(FATAL_ERROR "UPT-04 ray payload is not the frozen 32-byte compact hit-facts shape")
endif()

file(WRITE "${UPT04_STAMP}"
    "UPT-04 backend closure verified: live strides=176/112/112/64, set1 shared, hit facts=32, RayQuery=1 adapter, raygen=1 adapter\n")
