foreach(required UPT04_RAYQUERY_REFLECTION UPT04_RAYQUERY_DISASSEMBLY
        UPT04_DIAGNOSTIC_REFLECTION UPT04_DIAGNOSTIC_DISASSEMBLY
        UPT04_RAYGEN_REFLECTION UPT04_RAYGEN_DISASSEMBLY
        UPT04_MISS_DISASSEMBLY UPT04_CLOSEST_HIT_DISASSEMBLY
        UPT04_COMPACT_PRODUCTION_DISASSEMBLY
        UPT04_COMPACT_GEOMETRY_PACK_DISASSEMBLY
        UPT04_COMPACT_LIGHT_PACK_DISASSEMBLY UPT04_STAMP)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "UPT-04 backend verification missing ${required}")
    endif()
endforeach()

file(READ "${UPT04_RAYQUERY_REFLECTION}" rayquery_reflection)
file(READ "${UPT04_RAYQUERY_DISASSEMBLY}" rayquery_disassembly)
file(READ "${UPT04_DIAGNOSTIC_REFLECTION}" diagnostic_reflection)
file(READ "${UPT04_DIAGNOSTIC_DISASSEMBLY}" diagnostic_disassembly)
file(READ "${UPT04_RAYGEN_REFLECTION}" raygen_reflection)
file(READ "${UPT04_RAYGEN_DISASSEMBLY}" raygen_disassembly)
file(READ "${UPT04_MISS_DISASSEMBLY}" miss_disassembly)
file(READ "${UPT04_CLOSEST_HIT_DISASSEMBLY}" closest_hit_disassembly)
file(READ "${UPT04_COMPACT_PRODUCTION_DISASSEMBLY}" compact_production_disassembly)
file(READ "${UPT04_COMPACT_GEOMETRY_PACK_DISASSEMBLY}" compact_geometry_pack_disassembly)
file(READ "${UPT04_COMPACT_LIGHT_PACK_DISASSEMBLY}" compact_light_pack_disassembly)

foreach(kind compact_production compact_geometry_pack compact_light_pack)
    if(${kind}_disassembly MATCHES "OpCapability (Int16|Float16)" OR
       ${kind}_disassembly MATCHES "OpType(Int|Float) 16")
        message(FATAL_ERROR
            "UPT-04 ${kind} introduced native 16-bit SPIR-V without a device feature contract")
    endif()
endforeach()

foreach(kind rayquery raygen)
    foreach(stride 4 16 36 64 80 112 144 176)
        string(REGEX MATCHALL "\"array_stride\"[ \t]*:[ \t]*${stride}" stride_matches "${${kind}_reflection}")
        list(LENGTH stride_matches stride_count)
        if(stride EQUAL 112)
            set(expected_count 3)
        elseif(stride EQUAL 144 OR stride EQUAL 64)
            set(expected_count 2)
        elseif(stride EQUAL 16)
            # The unified production closure retains both the legacy emissive
            # replay lookup and the manager-owned power/area CDF.
            set(expected_count 2)
        else()
            set(expected_count 1)
        endif()
        if(NOT stride_count EQUAL expected_count)
            message(FATAL_ERROR
                "UPT-04 ${kind} has ${stride_count} declarations at stride ${stride}; expected ${expected_count}")
        endif()
    endforeach()
    if(NOT ${kind}_reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*25")
        message(FATAL_ERROR "UPT-04 ${kind} reflection lacks set 0 emissive-distribution binding 25")
    endif()
    foreach(binding 26 28 29)
        if(NOT ${kind}_reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
            message(FATAL_ERROR "UPT-04 ${kind} reflection lacks D0 previous-best binding ${binding}")
        endif()
    endforeach()
    foreach(binding RANGE 0 22)
        if(NOT ${kind}_reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
            message(FATAL_ERROR "UPT-04 ${kind} reflection lacks set 0 binding ${binding}")
        endif()
    endforeach()
    if(NOT ${kind}_reflection MATCHES "\"set\"[ \t]*:[ \t]*1,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*0")
        message(FATAL_ERROR "UPT-04 ${kind} reflection lacks shared set 1 texture binding")
    endif()
    string(REGEX MATCHALL "\"binding\"[ \t]*:" descriptor_bindings "${${kind}_reflection}")
    list(LENGTH descriptor_bindings descriptor_binding_count)
    if(NOT descriptor_binding_count EQUAL 28)
        message(FATAL_ERROR "UPT-04 ${kind} must expose exactly 28 descriptor bindings")
    endif()
    if(NOT ${kind}_reflection MATCHES "\"name\"[ \t]*:[ \t]*\"emissiveDistributionCountAndValid\",[ \t\r\n]*\"type\"[ \t]*:[ \t]*\"uint\",[ \t\r\n]*\"offset\"[ \t]*:[ \t]*188")
        message(FATAL_ERROR "UPT-04 ${kind} push constants are not the 192-byte D0 history layout")
    endif()
endforeach()

foreach(binding RANGE 0 23)
    if(NOT diagnostic_reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
        message(FATAL_ERROR "UPT-04 diagnostic reflection lacks set 0 binding ${binding}")
    endif()
endforeach()
if(NOT diagnostic_reflection MATCHES "\"set\"[ \t]*:[ \t]*1,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*0")
    message(FATAL_ERROR "UPT-04 diagnostic reflection lacks shared set 1 texture binding")
endif()
if(NOT diagnostic_reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*25")
    message(FATAL_ERROR "UPT-04 diagnostic reflection lacks set 0 emissive-distribution binding 25")
endif()
foreach(binding 26 28 29)
    if(NOT diagnostic_reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
        message(FATAL_ERROR "UPT-04 diagnostic reflection lacks D0 previous-best binding ${binding}")
    endif()
endforeach()
string(REGEX MATCHALL "\"binding\"[ \t]*:" diagnostic_bindings "${diagnostic_reflection}")
list(LENGTH diagnostic_bindings diagnostic_binding_count)
if(NOT diagnostic_binding_count EQUAL 29)
    message(FATAL_ERROR "UPT-04 diagnostic entry must expose exactly 29 descriptor bindings")
endif()
string(REGEX MATCHALL "OpRayQueryInitializeKHR" diagnostic_rayquery_instructions "${diagnostic_disassembly}")
list(LENGTH diagnostic_rayquery_instructions diagnostic_rayquery_instruction_count)
if(NOT diagnostic_rayquery_instruction_count EQUAL 3 OR diagnostic_disassembly MATCHES "OpTraceRayKHR")
    message(FATAL_ERROR "UPT-04 diagnostic closure must retain exactly three bounded trace sites")
endif()

if(NOT rayquery_reflection MATCHES "\"workgroup_size\"[ \t\r\n]*:[ \t\r\n]*\[[ \t\r\n]*8[ \t]*,[ \t\r\n]*8")
    message(FATAL_ERROR "UPT-04 RayQuery workgroup is not 8x8")
endif()
string(REGEX MATCHALL "OpRayQueryInitializeKHR" rayquery_instructions "${rayquery_disassembly}")
list(LENGTH rayquery_instructions rayquery_instruction_count)
if(NOT rayquery_instruction_count EQUAL 3 OR rayquery_disassembly MATCHES "OpTraceRayKHR")
    message(FATAL_ERROR "UPT-04 RayQuery closure must expose exactly three bounded trace sites")
endif()
string(REGEX MATCHALL "OpTraceRayKHR" traceray_instructions "${raygen_disassembly}")
list(LENGTH traceray_instructions traceray_instruction_count)
if(NOT traceray_instruction_count EQUAL 3 OR raygen_disassembly MATCHES "OpRayQueryInitializeKHR")
    message(FATAL_ERROR "UPT-04 raygen closure must expose exactly three bounded trace sites")
endif()
if(NOT miss_disassembly MATCHES "OpEntryPoint MissKHR")
    message(FATAL_ERROR "UPT-04 miss module is not a Vulkan miss stage")
endif()
if(NOT closest_hit_disassembly MATCHES "OpEntryPoint ClosestHitKHR")
    message(FATAL_ERROR "UPT-04 closest-hit module is not a Vulkan closest-hit stage")
endif()
if(NOT closest_hit_disassembly MATCHES "Upt04HitFacts = OpTypeStruct %uint %uint %uint %uint %v2float %float %uint")
    message(FATAL_ERROR "UPT-04 ray payload is not the frozen 32-byte compact hit-facts shape")
endif()

file(WRITE "${UPT04_STAMP}"
    "UPT-04 backend closure verified: production set0[0..22,25,26,28,29]+set1[0], diagnostic set0[0..23,25,26,28,29]+set1[0], live strides=4/16x2/36/64x2/80/112x3/144x2/176, push=192, hit facts=32, bounded trace sites=3, RayQuery/raygen adapters isolated, compact binary16 storage uses no native Int16/Float16 capability\n")
