foreach(required UPT04_BASELINE_REFLECTION UPT04_BASELINE_DISASSEMBLY
        UPT04_TEST_REFLECTION UPT04_TEST_DISASSEMBLY UPT04_STAMP)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "UPT-04 module verification missing ${required}")
    endif()
endforeach()

foreach(kind BASELINE TEST)
    file(READ "${UPT04_${kind}_REFLECTION}" reflection)
    file(READ "${UPT04_${kind}_DISASSEMBLY}" disassembly)
    if(NOT reflection MATCHES "\"array_stride\"[ \t]*:[ \t]*48")
        message(FATAL_ERROR "UPT-04 ${kind} surface stride is not 48 bytes")
    endif()
    if(NOT reflection MATCHES "\"array_stride\"[ \t]*:[ \t]*64")
        message(FATAL_ERROR "UPT-04 ${kind} reservoir stride is not 64 bytes")
    endif()
    if(NOT reflection MATCHES "\"workgroup_size\"[ \t\r\n]*:[ \t\r\n]*\[[ \t\r\n]*8[ \t]*,[ \t\r\n]*8")
        message(FATAL_ERROR "UPT-04 ${kind} workgroup is not 8x8")
    endif()
    string(REGEX MATCHALL "\"binding\"[ \t]*:" bindings "${reflection}")
    list(LENGTH bindings binding_count)
    if(NOT binding_count EQUAL 2)
        message(FATAL_ERROR "UPT-04 ${kind} probe must expose exactly two bindings")
    endif()
    if(disassembly MATCHES "OpTraceRay|OpRayQuery|RayTracingKHR|RayQueryKHR")
        message(FATAL_ERROR "UPT-04 ${kind} ownership probe unexpectedly traces rays")
    endif()
endforeach()

file(WRITE "${UPT04_STAMP}"
    "UPT-04 module graph verified: replaceable material set, explicit white-hash key, 48-byte surface, 64-byte reservoir, 8x8, rays=0\n")
