foreach(required UPT05_REFLECTION UPT05_DISASSEMBLY UPT05_STAMP)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "UPT-05 resolve verification missing ${required}")
    endif()
endforeach()

file(READ "${UPT05_REFLECTION}" reflection)
file(READ "${UPT05_DISASSEMBLY}" disassembly)

foreach(binding RANGE 0 2)
    if(NOT reflection MATCHES "\"set\"[ \t]*:[ \t]*0,[ \t\r\n]*\"binding\"[ \t]*:[ \t]*${binding}")
        message(FATAL_ERROR "UPT-05 resolve reflection lacks set 0 binding ${binding}")
    endif()
endforeach()
string(REGEX MATCHALL "\"binding\"[ \t]*:" bindings "${reflection}")
list(LENGTH bindings binding_count)
if(NOT binding_count EQUAL 3)
    message(FATAL_ERROR "UPT-05 resolve must expose exactly three descriptor bindings")
endif()
if(NOT reflection MATCHES "\"array_stride\"[ \t]*:[ \t]*64")
    message(FATAL_ERROR "UPT-05 resolve reservoir SRV is not stride 64")
endif()
if(NOT reflection MATCHES "\"workgroup_size\"[ \t\r\n]*:[ \t\r\n]*\[[ \t\r\n]*8[ \t]*,[ \t\r\n]*8")
    message(FATAL_ERROR "UPT-05 resolve workgroup is not 8x8")
endif()
if(NOT disassembly MATCHES "OpTypeImage %float 2D 2 0 0 2 Rgba16f")
    message(FATAL_ERROR "UPT-05 resolve output is not an rgba16f storage image")
endif()
if(disassembly MATCHES "OpTraceRayKHR|OpRayQuery|OpImageSample|OpImageFetch")
    message(FATAL_ERROR "UPT-05 resolve contains forbidden ray or texture-sampling work")
endif()

file(WRITE "${UPT05_STAMP}"
    "UPT-05 resolve verified: set0 bindings 0..2, reservoir stride 64, primary self-emission, rgba16f output, 8x8, trace-free and sample-free\n")
