if(NOT DEFINED UPT00_HARNESS OR NOT DEFINED UPT00_ARTIFACT_DIR)
    message(FATAL_ERROR "UPT00_HARNESS and UPT00_ARTIFACT_DIR are required")
endif()

set(trial_count 5)
foreach(order IN ITEMS slang-first dxc-first)
    foreach(trial RANGE 1 ${trial_count})
        set(report "${UPT00_ARTIFACT_DIR}/gpu_${order}_trial_${trial}.csv")
        execute_process(
            COMMAND "${UPT00_HARNESS}" "${UPT00_ARTIFACT_DIR}" "${report}" "${order}"
            RESULT_VARIABLE result
            OUTPUT_VARIABLE output
            ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "UPT-00 ${order} trial ${trial} failed:\n${output}\n${error}")
        endif()
        message(STATUS "${output}")
    endforeach()
endforeach()

set(summary "order,kernel,compiler,trials,median_first_pipeline_ms,median_warm_pipeline_ms,median_gpu_ms_per_dispatch,output_fnv1a64,readback_match\n")
foreach(order IN ITEMS slang-first dxc-first)
    string(REPLACE "-" "_" order_key "${order}")
    foreach(kernel IN ITEMS structured_math reservoir_update ray_query)
        foreach(compiler IN ITEMS slang dxc)
            set(first_values)
            set(warm_values)
            set(gpu_values)
            set(expected_hash "")
            foreach(trial RANGE 1 ${trial_count})
                set(report "${UPT00_ARTIFACT_DIR}/gpu_${order}_trial_${trial}.csv")
                file(STRINGS "${report}" rows)
                foreach(row IN LISTS rows)
                    if(row MATCHES ",${order},${kernel},${compiler},")
                        string(REPLACE "," ";" fields "${row}")
                        list(GET fields 7 first_ms)
                        list(GET fields 8 warm_ms)
                        list(GET fields 9 gpu_ms)
                        list(GET fields 10 output_hash)
                        list(GET fields 11 match)
                        if(NOT match STREQUAL "yes")
                            message(FATAL_ERROR "UPT-00 readback mismatch in ${report}: ${row}")
                        endif()
                        if(expected_hash AND NOT output_hash STREQUAL expected_hash)
                            message(FATAL_ERROR "UPT-00 unstable output hash for ${kernel}/${compiler}")
                        endif()
                        set(expected_hash "${output_hash}")
                        list(APPEND first_values "${first_ms}")
                        list(APPEND warm_values "${warm_ms}")
                        list(APPEND gpu_values "${gpu_ms}")
                    endif()
                endforeach()
            endforeach()
            list(LENGTH gpu_values value_count)
            if(NOT value_count EQUAL trial_count)
                message(FATAL_ERROR "Expected ${trial_count} samples for ${order}/${kernel}/${compiler}, found ${value_count}")
            endif()
            list(SORT first_values COMPARE NATURAL ORDER ASCENDING)
            list(SORT warm_values COMPARE NATURAL ORDER ASCENDING)
            list(SORT gpu_values COMPARE NATURAL ORDER ASCENDING)
            math(EXPR median_index "${trial_count} / 2")
            list(GET first_values ${median_index} median_first)
            list(GET warm_values ${median_index} median_warm)
            list(GET gpu_values ${median_index} median_gpu)
            string(APPEND summary "${order},${kernel},${compiler},${trial_count},${median_first},${median_warm},${median_gpu},${expected_hash},yes\n")
        endforeach()
    endforeach()
endforeach()

file(WRITE "${UPT00_ARTIFACT_DIR}/gpu_comparison_summary.csv" "${summary}")
message(STATUS "UPT-00 repeated-trial summary: ${UPT00_ARTIFACT_DIR}/gpu_comparison_summary.csv")
